<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'film_category_asc' => [[], ['_controller' => 'App\\Controller\\FilmCategoryController::index'], [], [['text', '/index/']], [], []],
    'film_category_desc' => [[], ['_controller' => 'App\\Controller\\FilmCategoryController::sortCategoryDESC'], [], [['text', '/index/index/desc']], [], []],
    'film_index' => [[], ['_controller' => 'App\\Controller\\FilmController::index'], [], [['text', '/movie/']], [], []],
    'film_title_asc' => [[], ['_controller' => 'App\\Controller\\FilmController::sortTitleASC'], [], [['text', '/movie/titre/asc']], [], []],
    'film_title_desc' => [[], ['_controller' => 'App\\Controller\\FilmController::sortTitleDESC'], [], [['text', '/movie/titre/desc']], [], []],
    'film_rental_asc' => [[], ['_controller' => 'App\\Controller\\FilmController::sortRentalASC'], [], [['text', '/movie/rental/asc']], [], []],
    'film_rental_desc' => [[], ['_controller' => 'App\\Controller\\FilmController::sortRentalDESC'], [], [['text', '/movie/rental/desc']], [], []],
    'film_new' => [[], ['_controller' => 'App\\Controller\\FilmController::new'], [], [['text', '/movie/new']], [], []],
    'film_show' => [['id'], ['_controller' => 'App\\Controller\\FilmController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/movie']], [], []],
    'film_edit' => [['id'], ['_controller' => 'App\\Controller\\FilmController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/movie']], [], []],
    'film_delete' => [['id'], ['_controller' => 'App\\Controller\\FilmController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/movie']], [], []],
];
